-- Alias de nombres de la SEC → código CUT.
-- Generado a partir de las muestras de GetPorFecha (2024-08-02, 2026-09-30, 2026-10-04).
-- Casos corregidos manualmente: Paiguano→Paihuano, Punitagui→Punitaqui,
-- Marchihue→Marchigüe, La Calera→Calera.
BEGIN;
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Antofagasta', 'Antofagasta', '02101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Antofagasta', 'Calama', '02201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Antofagasta', 'Tocopilla', '02301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Arica y Parinacota', 'Arica', '15101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Atacama', 'Alto del Carmen', '03302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Atacama', 'Copiapo', '03101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Atacama', 'Diego de Almagro', '03202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Atacama', 'Tierra Amarilla', '03103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Atacama', 'Vallenar', '03301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Aysén', 'Aysén', '11201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Aysén', 'Chile Chico', '11401');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Aysén', 'Cisnes', '11202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Aysén', 'Coyhaique', '11101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Alto Biobio', '08314');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Antuco', '08302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Arauco', '08202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Cabrero', '08303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Cañete', '08203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Chiguayante', '08103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Concepcion', '08101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Contulmo', '08204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Coronel', '08102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Curanilahue', '08205');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Florida', '08104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Hualpen', '08112');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Hualqui', '08105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Laja', '08304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Lebu', '08201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Los Alamos', '08206');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Los Angeles', '08301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Lota', '08106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Mulchen', '08305');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Nacimiento', '08306');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Negrete', '08307');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Penco', '08107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Quilaco', '08308');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Quilleco', '08309');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'San Pedro de la Paz', '08108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'San Rosendo', '08310');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Santa Barbara', '08311');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Santa Juana', '08109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Talcahuano', '08110');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Tirua', '08207');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Tome', '08111');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Tucapel', '08312');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Biobio', 'Yumbel', '08313');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Andacollo', '04103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Canela', '04202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Combarbala', '04302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Coquimbo', '04102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Illapel', '04201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'La Higuera', '04104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'La Serena', '04101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Los Vilos', '04203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Monte Patria', '04303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Ovalle', '04301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Paiguano', '04105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Punitagui', '04304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Rio Hurtado', '04305');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Salamanca', '04204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Coquimbo', 'Vicuña', '04106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Angol', '09201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Carahue', '09102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Cholchol', '09121');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Collipulli', '09202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Cunco', '09103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Curacautin', '09203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Curarrehue', '09104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Ercilla', '09204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Freire', '09105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Galvarino', '09106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Gorbea', '09107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Lautaro', '09108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Loncoche', '09109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Lonquimay', '09205');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Los Sauces', '09206');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Lumaco', '09207');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Melipeuco', '09110');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Nueva Imperial', '09111');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Padre Las Casas', '09112');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Perquenco', '09113');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Pitrufquen', '09114');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Pucon', '09115');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Puren', '09208');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Renaico', '09209');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Saavedra', '09116');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Temuco', '09101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Teodoro Schmidt', '09117');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Tolten', '09118');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Traiguen', '09210');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Victoria', '09211');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Vilcun', '09119');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'La Araucania', 'Villarrica', '09120');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Ancud', '10202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Calbuco', '10102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Castro', '10201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Chonchi', '10203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Cochamo', '10103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Curaco de Velez', '10204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Dalcahue', '10205');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Fresia', '10104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Frutillar', '10105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Hualaihue', '10403');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Llanquihue', '10107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Los Muermos', '10106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Maullin', '10108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Osorno', '10301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Puerto Montt', '10101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Puerto Octay', '10302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Puerto Varas', '10109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Puqueldon', '10206');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Purranque', '10303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Puyehue', '10304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Queilen', '10207');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Quellon', '10208');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Quemchi', '10209');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Quinchao', '10210');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'Rio Negro', '10305');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'San Juan de la Costa', '10306');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Lagos', 'San Pablo', '10307');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Futrono', '14202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'La Union', '14201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Lago Ranco', '14203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Lanco', '14103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Los Lagos', '14104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Mafil', '14105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Mariquina', '14106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Paillaco', '14107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Panguipulli', '14108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Rio Bueno', '14204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Los Rios', 'Valdivia', '14101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Magallanes', 'Natales', '12401');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Cauquenes', '07201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Chanco', '07202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Colbun', '07402');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Constitucion', '07102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Curepto', '07103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Curico', '07301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Empedrado', '07104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Hualañé', '07302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Licanten', '07303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Linares', '07401');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Longavi', '07403');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Maule', '07105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Molina', '07304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Parral', '07404');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Pelarco', '07106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Pelluhue', '07203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Pencahue', '07107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Rauco', '07305');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Retiro', '07405');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Rio Claro', '07108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Romeral', '07306');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Sagrada Familia', '07307');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'San Clemente', '07109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'San Javier', '07406');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'San Rafael', '07110');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Talca', '07101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Teno', '07308');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Vichuquen', '07309');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Villa Alegre', '07407');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Maule', 'Yerbas Buenas', '07408');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Alhue', '13502');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Buin', '13402');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Calera de Tango', '13403');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Cerrillos', '13102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Cerro Navia', '13103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Colina', '13301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Conchali', '13104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Curacavi', '13503');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'El Bosque', '13105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'El Monte', '13602');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Estacion Central', '13106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Huechuraba', '13107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Independencia', '13108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Isla de Maipo', '13603');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'La Cisterna', '13109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'La Florida', '13110');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'La Granja', '13111');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'La Pintana', '13112');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'La Reina', '13113');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Lampa', '13302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Las Condes', '13114');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Lo Barnechea', '13115');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Lo Espejo', '13116');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Lo Prado', '13117');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Macul', '13118');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Maipu', '13119');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Maria Pinto', '13504');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Melipilla', '13501');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Padre Hurtado', '13604');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Paine', '13404');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Pedro Aguirre Cerda', '13121');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Peñaflor', '13605');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Peñalolen', '13122');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Pirque', '13202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Providencia', '13123');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Pudahuel', '13124');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Puente Alto', '13201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Quilicura', '13125');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Quinta Normal', '13126');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Recoleta', '13127');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Renca', '13128');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'San Bernardo', '13401');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'San Joaquin', '13129');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'San Jose de Maipo', '13203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'San Miguel', '13130');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'San Pedro', '13505');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'San Ramon', '13131');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Santiago', '13101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Talagante', '13601');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Tiltil', '13303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Vitacura', '13132');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Metropolitana', 'Ñuñoa', '13120');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Chepica', '06302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Chimbarongo', '06303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Codegua', '06102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Coinco', '06103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Coltauco', '06104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Doñihue', '06105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Graneros', '06106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'La Estrella', '06202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Las Cabras', '06107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Litueche', '06203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Lolol', '06304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Machali', '06108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Malloa', '06109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Marchihue', '06204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Mostazal', '06110');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Nancagua', '06305');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Navidad', '06205');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Olivar', '06111');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Palmilla', '06306');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Paredones', '06206');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Peralillo', '06307');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Peumo', '06112');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Pichidegua', '06113');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Pichilemu', '06201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Placilla', '06308');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Pumanque', '06309');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Quinta de Tilcoco', '06114');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Rancagua', '06101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Rengo', '06115');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Requinoa', '06116');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'San Fernando', '06301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'San Vicente', '06117');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'O`Higgins', 'Santa Cruz', '06310');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Tarapaca', 'Alto Hospicio', '01107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Tarapaca', 'Iquique', '01101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Tarapaca', 'Pica', '01405');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Tarapaca', 'Pozo Almonte', '01401');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Algarrobo', '05602');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Cabildo', '05402');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Calle Larga', '05302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Cartagena', '05603');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Casablanca', '05102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Catemu', '05702');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Concon', '05103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'El Quisco', '05604');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'El Tabo', '05605');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'La Calera', '05502');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'La Cruz', '05504');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'La Ligua', '05401');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Limache', '05802');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Llaillay', '05703');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Los Andes', '05301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Nogales', '05506');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Olmue', '05803');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Papudo', '05403');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Petorca', '05404');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Puchuncavi', '05105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Putaendo', '05705');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Quillota', '05501');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Quilpue', '05801');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Quintero', '05107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Rinconada', '05303');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'San Antonio', '05601');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'San Esteban', '05304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'San Felipe', '05701');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Santa Maria', '05706');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Santo Domingo', '05606');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Valparaiso', '05101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Villa Alemana', '05804');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Viña del Mar', '05109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Valparaiso', 'Zapallar', '05405');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Bulnes', '16102');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Chillan', '16101');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Chillan Viejo', '16103');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Cobquecura', '16202');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Coelemu', '16203');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Coihueco', '16302');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'El Carmen', '16104');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Ninhue', '16204');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Pemuco', '16105');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Pinto', '16106');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Portezuelo', '16205');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Quillón', '16107');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Quirihue', '16201');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Ranquil', '16206');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'San Carlos', '16301');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'San Fabian', '16304');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'San Ignacio', '16108');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'San Nicolas', '16305');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Treguaco', '16207');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Yungay', '16109');
INSERT INTO comuna_aliases (source, raw_region, raw_comuna, cut) VALUES ('sec', 'Ñuble', 'Ñiquén', '16303');
COMMIT;
